### ISSUE TITLE
Parameter documentation

### ISSUE THREAD

**Issue by frankvdh** [felipesanches/OpenSCAD_Voronoi_Generator#2]
A little documentation that I figured out regarding the L, thickness, and round parameters to the voronoi() module (I really should learn how to do the pull request thing, but until then I'll just submit this as an issue...)

L is the radius of the "world"... the pattern is built within this circle.
thickness is the thickness of the lines between cells
round is the radius applied to corners (fillet in CAD terms).

These parameters need to be kept more or less in proportion to each other, and to the distance apart of points in the point_set. If one or the other parameter is increased or decreased too much, you'll get no output.

The voronoi() function generates a 2D surface, which can be provided to
a) linear_extrude() to produce a 3D object
b) intersection() to restrict it to a a specified shape

Hope this helps someone,
Frank

**Comment by felipesanches** [comment]
hey! Thanks!

I'll review it all later this week.
